### PR TITLE
fix(bridge): catch KeyError when device gets unavailable

### PR DESCRIPTION
**Pull request by pree**
When a device gets unavailable (i.e. when the battery runs out) it throws a KeyError. Catching it results in still getting a response from the other devices.

### CODE REVIEW

**Comment by pree** [comment]
Hey @pschmitt do you have any concerns about this PR? If possible I'd like to bump the version on Home Assistant for both PR's when possible :)

**Comment by pschmitt** [comment]
No concerns, just not much time. I'm currently battling several Ikea Paxes ;)

**Comment by pschmitt** [comment]
https://pypi.org/project/pynuki/1.5.1/

**Comment by pschmitt** [comment]
https://pypi.org/project/pynuki/1.5.0/

**Pull request merged**
