### PR TITLE
Add method to update state from a callback

### PR DESCRIPTION
**Pull request by steinerl**
Hi,

I've added a method to update the JSON state of a `NukiDevice` from an external caller (e.g. a callback/webhook).

For context: I'm working on switching the Home Assistant Nuki component from polling to Bridge callbacks.

### CODE REVIEW

**Comment by pschmitt** [comment]
I don't get why this is required for what you are trying to do here. Is there some code I can look at?

**Comment by steinerl** [comment]
The Nuki Bridge is going to call a Home Assistant webhook and the webhook handler should be able to update the state of the NukiDevice without directly accessing the `_json` attribute.

Have I overlooked something, is there already a clean method/setter?

**Comment by pschmitt** [comment]
Yeah, okay that makes sense. Setting `_json` directly is what I had in mind. But you are right, this isn't exactly the correct way.
I'd have implemented it differently though (using a property or adding an arg to the `update` function maybe?). Hmm, anyway imma merge this as is. Thanks!

**Comment by pschmitt** [comment]
This is part of 1.4.1

**Comment by steinerl** [comment]
I thought about implementing it using a property too, but the `_json` object consists of 'device data' and 'state data' and the callback only updates 'state data', so a simple setter would be misleading IMHO.
I didn't want to touch/change the signature of the `update` method (for compatibility reasons) either.

Anyway, thanks for merging!

**Comment by Alfiegerner** [comment]
Hi @steinerl - can I ask how you update the state via webhooks? I was thinking of doing the same but figure we'd need a new service exposed in HomeAssistant.

**Pull request merged**
